### ISSUE TITLE
YTS.AG is no longer responding here

### ISSUE THREAD

**Issue by inthewazyzz** [mancuniancol/plugin.video.yts#6] opened 2016-11-16 17:47 UTC
Can you add support for https://yts.gs

**Comment by mancuniancol** [comment] 2016-11-16 17:51
Did you change the Url in the settings? And is it not working?

**Comment by inthewazyzz** [comment] 2016-11-16 17:54
Due to the website blockade in some countries sadly .ag is one of them blocked. gs is working but your add-on doesn't load anything after "Latest".

**Comment by mancuniancol** [comment] 2016-11-16 18:04
I will check it

**Comment by mancuniancol** [comment] 2016-11-16 23:55
The url works without any problem.  Please, disable the metainfomation because it is possible that it is making too slow.   You can also configure the metahandler script with a TheMovieDB key, you can get it for free, just creating an account.

**Comment by mancuniancol** [comment] 2016-11-16 23:56
I will close this issue, because I couldn't reproduce in my side and it seems a problem with metainformation.

**Closed by mancuniancol** 2016-11-16 23:56 UTC
